### ISSUE TITLE
Touchbar works as a touchpad

### ISSUE THREAD

**Issue by yoonjin2** [leifliddy/asahi-rocky-builder#1]
Touchbar support is strange on Rocky Linux. I tested it with linux 6.6.3 fedora, but I cannot detect this. Do you have any plan to port it into rocky linux?

**Comment by leifliddy** [comment]
lol...I didn't realize anyone was actually using this build ; )

So `tiny-dfr` is the rust package that controls the touchbar.
And it was the one package that I wasn't able to compile on el9.

rust spec files have dynamic build dependencies -- so you have to build them with `mock`. 
ie 
```
[root@rpm_builder_el9 SPECS]# mock --sources ../SOURCES/ --spec rust-tiny-dfr.spec
....
Error: 
 Problem 1: nothing provides requested (crate(cairo-rs) >= 0.18.0 with crate(cairo-rs) < 0.19.0~)
 Problem 2: nothing provides requested (crate(cairo-rs/freetype) >= 0.18.0 with crate(cairo-rs/freetype) < 0.19.0~)
 Problem 3: nothing provides requested (crate(drm/default) >= 0.11.1 with crate(drm/default) < 0.12.0~)
 Problem 4: nothing provides requested (crate(freetype-rs/default) >= 0.32.0 with crate(freetype-rs/default) < 0.33.0~)
 Problem 5: nothing provides requested (crate(input-linux-sys/default) >= 0.8.0 with crate(input-linux-sys/default) < 0.9.0~)
 Problem 6: nothing provides requested (crate(input-linux/default) >= 0.6.0 with crate(input-linux/default) < 0.7.0~)
 Problem 7: nothing provides requested (crate(input-linux/serde) >= 0.6.0 with crate(input-linux/serde) < 0.7.0~)
 Problem 8: nothing provides requested (crate(input/default) >= 0.8.0 with crate(input/default) < 0.9.0~)
 Problem 9: nothing provides requested (crate(librsvg/default) >= 2.56.0 with crate(librsvg/default) < 3.0.0~)
 Problem 10: nothing provides requested (crate(privdrop/default) >= 0.5.3 with crate(privdrop/default) < 0.6.0~)
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Sometimes, you can just install the Fedora version of a package -- but in this case `glibc` is too new
ie
```
[root@rpm_builder_el9]# rpm -ivh tiny-dfr-0.2.0-2.fc39.aarch64.rpm
warning: tiny-dfr-0.2.0-2.fc39.aarch64.rpm: Header V4 RSA/SHA256 Signature, key ID 18b8e74c: NOKEY
error: Failed dependencies:
	libm.so.6(GLIBC_2.38)(64bit) is needed by tiny-dfr-0.2.0-2.fc39.aarch64
```

Actually, you can install the Fedora 38 version of this package on a el9 system. 
```
[root@rpm_builder_9]# rpm -ivh tiny-dfr-0.1.2-2.fc38.aarch64.rpm
warning: tiny-dfr-0.1.2-2.fc38.aarch64.rpm: Header V4 RSA/SHA256 Signature, key ID eb10b464: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:tiny-dfr-0.1.2-2.fc38            ################################# [100%]
```

That's interesting. Ok, I can build a version of this package on a F38 system --> for EL9. 
I'm a bit busy atm, might need a day or two before I get to it.....

**Comment by yoonjin2** [comment]
thanks:)

**Comment by leifliddy** [comment]
Wow...that was a bit of work
I had to create a ton of rust crates for this to work.
https://leifliddy.com/asahi-linux/38/aarch64/

Afterwards I could compile the `tiny-dfr` in a custom F38 mock environment -- and just renamed the distro tag to el9. 

The latest version `tiny-dfr-0.2.0-2.el9` now in the el9 repo
https://leifliddy.com/asahi-linux/9/aarch64/

Can you please install it and report back on weather it works or not?
```dnf install tiny-dfr --refresh```

If it does work -- I'll include it in the image. 
I don't have any devices with touchbars, so I can't test it myself

**Comment by yoonjin2** [comment]
thank you!
